In [2]:
import pandas as pd
from tqdm import tqdm
from tqdm.notebook import tqdm
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)

In [14]:
people_df = pd.read_csv('/vast/amr10211/people-db-people-2023-08-31.csv.bz2')
people_positions_df = pd.read_csv('/vast/amr10211/people-db-positions-2023-08-31.csv.bz2')
# people_positions_df = people_positions_df.rename(columns={'person_id': 'original_person_id'})
# people_positions_df = people_positions_df.rename(columns={'id': 'person_id'})
people_df = people_positions_df.merge(people_df, how ='left', left_on='person_id', right_on='id')


president_df = people_df[people_df['position_type']=='pres']
president_df = president_df[['person_id', 'slug', 'date_start', 'date_termination']]
president_df = president_df.rename(columns={'person_id': 'president_id', 'slug': 'president_name'})
president_df.head(100)

/state/partition1/job-40547856/ipykernel_3973755/503787167.py:2: DtypeWarning: Columns (11,12,13,14,22,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  people_positions_df = pd.read_csv('/vast/amr10211/people-db-positions-2023-08-31.csv.bz2')

       president_id             president_name  date_start date_termination
18538          8521          donald-john-trump  2017-01-20       2021-01-20
32816            26        william-howard-taft  1909-01-01       1913-01-01
33267             1          george-washington  1789-01-01       1797-01-01
33268             2                 john-adams  1797-01-01       1801-01-01
33269             3           thomas-jefferson  1801-01-01       1809-01-01
33270             4              james-madison  1809-01-01       1817-01-01
33271             5               james-monroe  1817-01-01       1825-01-01
33272             6          john-quincy-adams  1825-01-01       1829-01-01
33273             7             andrew-jackson  1829-01-01       1837-01-01
33274             8           martin-van-buren  1837-01-01       1841-01-01
33275             9     william-henry-harrison  1841-01-01       1841-01-01
33276            10                 john-tyler  1841-01-01       1845-01-01
33277            11               james-k-polk  1845-01-01       1849-01-01
33278            12             zachary-taylor  1849-01-01       1850-01-01
33279            13           millard-fillmore  1850-01-01       1853-01-01
33280            14            franklin-pierce  1853-01-01       1857-01-01
33281            15             james-buchanan  1857-01-01       1861-01-01
33282            16            abraham-lincoln  1861-01-01       1865-01-01
33283            17             andrew-johnson  1865-01-01       1869-01-01
33284            18            ulysses-s-grant  1869-01-01       1877-01-01
33285            19         rutherford-b-hayes  1877-01-01       1881-01-01
33286            20           james-a-garfield  1881-01-01       1881-01-01
33287            21             chester-arthur  1881-01-01       1885-01-01
33288            22           grover-cleveland  1885-01-01       1889-01-01
33289            22           grover-cleveland  1893-01-01       1897-01-01
33290            23          benjamin-harrison  1889-01-01       1893-01-01
33291            24           william-mckinley  1897-01-01       1901-01-01
33292            25         theodore-roosevelt  1901-01-01       1909-01-01
33293            27             woodrow-wilson  1913-01-01       1921-01-01
33294            28           warren-g-harding  1921-01-01       1923-01-01
33295            29            calvin-coolidge  1923-01-01       1929-01-01
33296            30             herbert-hoover  1929-01-01       1933-01-01
33297            31       franklin-d-roosevelt  1933-01-01       1945-01-01
33298            32             harry-s-truman  1945-01-01       1953-01-01
33299            33          dwight-eisenhower  1953-01-01       1961-01-01
33300            34             john-f-kennedy  1961-01-01       1963-01-01
33301            35           lyndon-b-johnson  1963-01-01       1969-01-01
33302            36              richard-nixon  1969-01-01       1974-01-01
33303            37                gerald-ford  1974-01-01       1977-01-01
33304            38               jimmy-carter  1977-01-01       1981-01-01
33305            39              ronald-reagan  1981-01-01       1989-01-01
33306            40             george-hw-bush  1989-01-01       1993-01-01
33307            41  william-jefferson-clinton  1993-01-01       2001-01-01
33308            42              george-w-bush  2001-01-01       2009-01-01
33309            43    barack-hussein-obama-ii  2009-01-01       2017-01-01
44165         14437  joseph-robinette-biden-jr  2021-01-20              NaN

In [12]:
people_positions_df = pd.read_csv('/vast/amr10211/people-db-positions-2023-08-31.csv.bz2')

/state/partition1/job-40547856/ipykernel_3973755/936221926.py:1: DtypeWarning: Columns (11,12,13,14,22,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  people_positions_df = pd.read_csv('/vast/amr10211/people-db-positions-2023-08-31.csv.bz2')

In [13]:
people_positions_df[people_positions_df['position_type']=='pres']

,id,date_created,date_modified,position_type,job_title,sector,organization_name,location_city,location_state,date_nominated,date_elected,date_recess_appointment,date_referred_to_judicial_committee,date_judicial_committee_action,judicial_committee_action,date_hearing,date_confirmation,date_start,date_granularity_start,date_termination,termination_reason,date_granularity_termination,date_retirement,nomination_process,vote_type,voice_vote,votes_yes,votes_no,votes_yes_percent,votes_no_percent,how_selected,has_inferred_values,appointer_id,court_id,person_id,predecessor_id,school_id,supervisor_id
18538,33612,2017-06-27 18:40:27.632548+00,2023-03-31 14:19:53.73449+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-20,%Y-%m-%d,2021-01-20,lost,%Y-%m-%d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,8521,NaN,NaN,NaN
32816,27,2016-04-20 15:15:48.38703+00,2016-04-20 16:05:42.422832+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909-01-01,%Y,1913-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,26,NaN,NaN,NaN
33267,1,2016-04-20 15:15:47.565552+00,2016-04-20 15:15:47.565585+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1789-01-01,%Y,1797-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,1,NaN,NaN,NaN
33268,2,2016-04-20 15:15:47.61362+00,2016-04-20 15:15:47.613649+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1797-01-01,%Y,1801-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,2,NaN,NaN,NaN
33269,3,2016-04-20 15:15:47.646673+00,2016-04-20 15:15:47.646711+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1801-01-01,%Y,1809-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,3,NaN,NaN,NaN
33270,4,2016-04-20 15:15:47.681913+00,2016-04-20 15:15:47.68194+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1809-01-01,%Y,1817-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,4,NaN,NaN,NaN
33271,5,2016-04-20 15:15:47.711494+00,2016-04-20 15:15:47.711519+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1817-01-01,%Y,1825-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,5,NaN,NaN,NaN
33272,6,2016-04-20 15:15:47.745059+00,2016-04-20 15:15:47.745083+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1825-01-01,%Y,1829-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,6,NaN,NaN,NaN
33273,7,2016-04-20 15:15:47.777023+00,2016-04-20 15:15:47.777045+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1829-01-01,%Y,1837-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,7,NaN,NaN,NaN
33274,8,2016-04-20 15:15:47.80971+00,2016-04-20 15:15:47.809732+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1837-01-01,%Y,1841-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,8,NaN,NaN,NaN
33275,9,2016-04-20 15:15:47.835687+00,2016-04-20 15:15:47.835707+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1841-01-01,%Y,1841-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,9,NaN,NaN,NaN
33276,10,2016-04-20 15:15:47.877317+00,2016-04-20 15:15:47.877354+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1841-01-01,%Y,1845-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,10,NaN,NaN,NaN
33277,11,2016-04-20 15:15:47.907846+00,2016-04-20 15:15:47.907867+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1845-01-01,%Y,1849-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,11,NaN,NaN,NaN
33278,12,2016-04-20 15:15:47.939222+00,2016-04-20 15:15:47.939244+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1849-01-01,%Y,1850-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,12,NaN,NaN,NaN
33279,13,2016-04-20 15:15:47.974884+00,2016-04-20 15:15:47.974906+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1850-01-01,%Y,1853-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,13,NaN,NaN,NaN
33280,14,2016-04-20 15:15:48.006694+00,2016-04-20 15:15:48.006744+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1853-01-01,%Y,1857-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,14,NaN,NaN,NaN
33281,15,2016-04-20 15:15:48.037087+00,2016-04-20 15:15:48.037108+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1857-01-01,%Y,1861-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,15,NaN,NaN,NaN
33282,16,2016-04-20 15:15:48.069238+00,2016-04-20 15:15:48.06926+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1861-01-01,%Y,1865-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,16,NaN,NaN,NaN
33283,17,2016-04-20 15:15:48.100147+00,2016-04-20 15:15:48.100168+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1865-01-01,%Y,1869-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,17,NaN,NaN,NaN
33284,18,2016-04-20 15:15:48.134893+00,2016-04-20 15:15:48.134919+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1869-01-01,%Y,1877-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,18,NaN,NaN,NaN
33285,19,2016-04-20 15:15:48.163807+00,2016-04-20 15:15:48.16383+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1877-01-01,%Y,1881-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,19,NaN,NaN,NaN
33286,20,2016-04-20 15:15:48.196407+00,2016-04-20 15:15:48.196429+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1881-01-01,%Y,1881-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,20,NaN,NaN,NaN
33287,21,2016-04-20 15:15:48.223321+00,2016-04-20 15:15:48.223358+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1881-01-01,%Y,1885-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,21,NaN,NaN,NaN
33288,22,2016-04-20 15:15:48.261472+00,2016-04-20 15:15:48.261494+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1885-01-01,%Y,1889-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,22,NaN,NaN,NaN
33289,23,2016-04-20 15:15:48.269297+00,2016-04-20 15:15:48.269319+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1893-01-01,%Y,1897-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,22,NaN,NaN,NaN
33290,24,2016-04-20 15:15:48.296799+00,2016-04-20 15:15:48.296821+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1889-01-01,%Y,1893-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,23,NaN,NaN,NaN
33291,25,2016-04-20 15:15:48.32832+00,2016-04-20 15:15:48.328342+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1897-01-01,%Y,1901-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,24,NaN,NaN,NaN
33292,26,2016-04-20 15:15:48.355943+00,2016-04-20 15:15:48.355964+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901-01-01,%Y,1909-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,25,NaN,NaN,NaN
33293,28,2016-04-20 15:15:48.419338+00,2016-04-20 15:15:48.419359+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1913-01-01,%Y,1921-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,27,NaN,NaN,NaN
33294,29,2016-04-20 15:15:48.450916+00,2016-04-20 15:15:48.450955+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1921-01-01,%Y,1923-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,28,NaN,NaN,NaN
33295,30,2016-04-20 15:15:48.489428+00,2016-04-20 15:15:48.489459+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1923-01-01,%Y,1929-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,29,NaN,NaN,NaN
33296,31,2016-04-20 15:15:48.52466+00,2016-04-20 15:15:48.524689+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1929-01-01,%Y,1933-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,30,NaN,NaN,NaN
33297,32,2016-04-20 15:15:48.558268+00,2016-04-20 15:15:48.558291+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1933-01-01,%Y,1945-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,31,NaN,NaN,NaN
33298,33,2016-04-20 15:15:48.589093+00,2016-04-20 15:15:48.589113+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945-01-01,%Y,1953-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,32,NaN,NaN,NaN
33299,34,2016-04-20 15:15:48.621322+00,2016-04-20 15:15:48.621355+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953-01-01,%Y,1961-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,33,NaN,NaN,NaN
33300,35,2016-04-20 15:15:48.651089+00,2016-04-20 15:15:48.65111+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1961-01-01,%Y,1963-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,34,NaN,NaN,NaN
33301,36,2016-04-20 15:15:48.678889+00,2016-04-20 15:15:48.67891+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963-01-01,%Y,1969-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,35,NaN,NaN,NaN
33302,37,2016-04-20 15:15:48.708414+00,2016-04-20 15:15:48.708435+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1969-01-01,%Y,1974-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,36,NaN,NaN,NaN
33303,38,2016-04-20 15:15:48.736115+00,2016-04-20 15:15:48.736135+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1974-01-01,%Y,1977-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,37,NaN,NaN,NaN
33304,39,2016-04-20 15:15:48.766746+00,2016-04-20 15:15:48.766774+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1977-01-01,%Y,1981-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,38,NaN,NaN,NaN
33305,40,2016-04-20 15:15:48.797256+00,2016-04-20 15:15:48.797281+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1981-01-01,%Y,1989-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,39,NaN,NaN,NaN
33306,41,2016-04-20 15:15:48.828832+00,2016-04-20 15:15:48.828853+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1989-01-01,%Y,1993-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,40,NaN,NaN,NaN
33307,42,2016-04-20 15:15:48.861026+00,2016-04-20 15:15:48.861048+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993-01-01,%Y,2001-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,41,NaN,NaN,NaN
33308,43,2016-04-20 15:15:48.891335+00,2016-04-20 15:15:48.891357+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-01,%Y,2009-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,42,NaN,NaN,NaN
33309,44,2016-04-20 15:15:48.921993+00,2016-04-20 15:15:48.922014+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-01-01,%Y,2017-01-01,NaN,%Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,43,NaN,NaN,NaN
44165,44243,2021-12-22 19:48:35.843435+00,2021-12-22 19:48:35.843478+00,pres,NaN,NaN,NaN,Washington,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-20,%Y-%m-%d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,14437,NaN,NaN,NaN